version: '3.7'

services:
  1edge-mongodb:
    image: mongo:latest
    restart: always
    container_name: 1edge-mongodb
    ports:
     - 27017:27017
    volumes:
      - ./shared_data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: OneEdgeDBUser
      MONGO_INITDB_ROOT_PASSWORD: OneEdgeDBPWS
    networks: 
      database:

  # 1edge-auth:
  #   image: "node:15.3"
  #   container_name: 1edge-auth
  #   working_dir: /home/node/app/1edge/backend/ms/auth
  #   volumes:
  #     - ./shared_data:/home/node/1edge/ms/auth/shared_data/logs
  #     - ./SourceCode/backend/common:/home/node/app/1edge/backend/common
  #     - ./SourceCode/backend/microservices/auth:/home/node/app/1edge/backend/ms/auth
  #   environment:
  #     - NODE_ENV=$NODE_ENV
  #   ports:
  #     - "3002:3001" 
  #   depends_on:
  #     - 1edge-mongodb
  #   command:
  #     - /bin/bash
  #     - -c
  #     - npm start
  #   networks:
  #     backend:

  # 1edge-tenants:
  #   image: "node:15.3"
  #   container_name: 1edge-tenants
  #   working_dir: /home/node/app/1edge/backend/ms/tenants
  #   volumes:
  #     - ./shared_data:/home/node/1edge/ms/tenants/shared_data/logs
  #     - ./SourceCode/backend/common:/home/node/app/1edge/backend/common
  #     - ./SourceCode/backend/microservices/tenants:/home/node/app/1edge/backend/ms/tenants
  #   environment:
  #     - NODE_ENV=$NODE_ENV
  #   ports:
  #     - "3003:3001" 
  #   depends_on:
  #     - 1edge-mongodb
  #   command:
  #     - /bin/bash
  #     - -c
  #     - npm start
  #   networks:
  #     backend:

  # 1edge-billing:
  #   image: "node:15.3"
  #   container_name: 1edge-billing
  #   working_dir: /home/node/app/1edge/backend/ms/billing
  #   volumes:
  #     - ./shared_data:/home/node/1edge/ms/billing/shared_data/logs
  #     - ./SourceCode/backend/common:/home/node/app/1edge/backend/common
  #     - ./SourceCode/backend/microservices/billing:/home/node/app/1edge/backend/ms/billing
  #   environment:
  #     - NODE_ENV=$NODE_ENV
  #   ports:
  #     - "3004:3001" 
  #   depends_on:
  #     - 1edge-mongodb
  #   command:
  #     - /bin/bash
  #     - -c
  #     - npm start
  #   networks:
  #     backend:

networks:
  database:
  backend: